
event.register("magicEffectsResolved", function ()
	require("OperatorJack.Vampyr.modules.magic-effects.auspex")()
	require("OperatorJack.Vampyr.modules.magic-effects.bloodstorm")()
	require("OperatorJack.Vampyr.modules.magic-effects.transfuse-blood")()
	require("OperatorJack.Vampyr.modules.magic-effects.fortify-claws")()
	require("OperatorJack.Vampyr.modules.magic-effects.glamour")()
	require("OperatorJack.Vampyr.modules.magic-effects.mistform")()
	require("OperatorJack.Vampyr.modules.magic-effects.resist-sun-damage")()
	require("OperatorJack.Vampyr.modules.magic-effects.restore-blood")()
end)